[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
cmd = 'cd backend-nestjs && npm ci'

[phases.build] 
cmd = 'cd backend-nestjs && npx prisma generate && npm run build'

[start]
cmd = 'cd backend-nestjs && npm run start:prod'

[variables]
NODE_ENV = 'production'
