[build]
buildCommand = "cd backend-nestjs && npm ci && npx prisma generate && npm run build"

[deploy]
startCommand = "cd backend-nestjs && npm run start:prod"
healthcheckPath = "/health"
healthcheckTimeout = 300

[env]
NODE_ENV = "production"
