services:
  - type: web
    name: modooui-backend
    env: node
    region: oregon
    plan: free
    rootDir: backend-nestjs
    buildCommand: npm ci && npx prisma generate && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: ALLOWED_ORIGINS
        value: https://modooui-service-platform.vercel.app,http://localhost:3000

databases:
  - name: postgres
    databaseName: modooui
    user: modooui
